spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

db-config:
  url: ${URL_DB_PG}
  user: ${USER}
  password: ${PASSWORD}
  