version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest-with-spring-boot
    ports:
      - "15432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:15432/rest-with-spring-boot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge